// Generated by gencpp from file collect_velo_data/collect_veloResult.msg
// DO NOT EDIT!


#ifndef COLLECT_VELO_DATA_MESSAGE_COLLECT_VELORESULT_H
#define COLLECT_VELO_DATA_MESSAGE_COLLECT_VELORESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/TransformStamped.h>
#include <geometry_msgs/TransformStamped.h>
#include <geometry_msgs/TransformStamped.h>

namespace collect_velo_data
{
template <class ContainerAllocator>
struct collect_veloResult_
{
  typedef collect_veloResult_<ContainerAllocator> Type;

  collect_veloResult_()
    : result_rotation()
    , ts_ptu()
    , ts_rs()  {
    }
  collect_veloResult_(const ContainerAllocator& _alloc)
    : result_rotation(_alloc)
    , ts_ptu(_alloc)
    , ts_rs(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::TransformStamped_<ContainerAllocator>  _result_rotation_type;
  _result_rotation_type result_rotation;

   typedef  ::geometry_msgs::TransformStamped_<ContainerAllocator>  _ts_ptu_type;
  _ts_ptu_type ts_ptu;

   typedef  ::geometry_msgs::TransformStamped_<ContainerAllocator>  _ts_rs_type;
  _ts_rs_type ts_rs;





  typedef boost::shared_ptr< ::collect_velo_data::collect_veloResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::collect_velo_data::collect_veloResult_<ContainerAllocator> const> ConstPtr;

}; // struct collect_veloResult_

typedef ::collect_velo_data::collect_veloResult_<std::allocator<void> > collect_veloResult;

typedef boost::shared_ptr< ::collect_velo_data::collect_veloResult > collect_veloResultPtr;
typedef boost::shared_ptr< ::collect_velo_data::collect_veloResult const> collect_veloResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::collect_velo_data::collect_veloResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::collect_velo_data::collect_veloResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::collect_velo_data::collect_veloResult_<ContainerAllocator1> & lhs, const ::collect_velo_data::collect_veloResult_<ContainerAllocator2> & rhs)
{
  return lhs.result_rotation == rhs.result_rotation &&
    lhs.ts_ptu == rhs.ts_ptu &&
    lhs.ts_rs == rhs.ts_rs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::collect_velo_data::collect_veloResult_<ContainerAllocator1> & lhs, const ::collect_velo_data::collect_veloResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace collect_velo_data

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::collect_velo_data::collect_veloResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::collect_velo_data::collect_veloResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::collect_velo_data::collect_veloResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::collect_velo_data::collect_veloResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::collect_velo_data::collect_veloResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::collect_velo_data::collect_veloResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::collect_velo_data::collect_veloResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "593509ac84d519f457e1f20b78510e22";
  }

  static const char* value(const ::collect_velo_data::collect_veloResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x593509ac84d519f4ULL;
  static const uint64_t static_value2 = 0x57e1f20b78510e22ULL;
};

template<class ContainerAllocator>
struct DataType< ::collect_velo_data::collect_veloResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "collect_velo_data/collect_veloResult";
  }

  static const char* value(const ::collect_velo_data::collect_veloResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::collect_velo_data::collect_veloResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"geometry_msgs/TransformStamped result_rotation\n"
"geometry_msgs/TransformStamped ts_ptu\n"
"geometry_msgs/TransformStamped ts_rs\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TransformStamped\n"
"# This expresses a transform from coordinate frame header.frame_id\n"
"# to the coordinate frame child_frame_id\n"
"#\n"
"# This message is mostly used by the \n"
"# <a href=\"http://wiki.ros.org/tf\">tf</a> package. \n"
"# See its documentation for more information.\n"
"\n"
"Header header\n"
"string child_frame_id # the frame id of the child frame\n"
"Transform transform\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Transform\n"
"# This represents the transform between two coordinate frames in free space.\n"
"\n"
"Vector3 translation\n"
"Quaternion rotation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::collect_velo_data::collect_veloResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::collect_velo_data::collect_veloResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result_rotation);
      stream.next(m.ts_ptu);
      stream.next(m.ts_rs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct collect_veloResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::collect_velo_data::collect_veloResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::collect_velo_data::collect_veloResult_<ContainerAllocator>& v)
  {
    s << indent << "result_rotation: ";
    s << std::endl;
    Printer< ::geometry_msgs::TransformStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.result_rotation);
    s << indent << "ts_ptu: ";
    s << std::endl;
    Printer< ::geometry_msgs::TransformStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.ts_ptu);
    s << indent << "ts_rs: ";
    s << std::endl;
    Printer< ::geometry_msgs::TransformStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.ts_rs);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COLLECT_VELO_DATA_MESSAGE_COLLECT_VELORESULT_H
