// Generated by gencpp from file collect_velo_data/collect_veloActionGoal.msg
// DO NOT EDIT!


#ifndef COLLECT_VELO_DATA_MESSAGE_COLLECT_VELOACTIONGOAL_H
#define COLLECT_VELO_DATA_MESSAGE_COLLECT_VELOACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <collect_velo_data/collect_veloGoal.h>

namespace collect_velo_data
{
template <class ContainerAllocator>
struct collect_veloActionGoal_
{
  typedef collect_veloActionGoal_<ContainerAllocator> Type;

  collect_veloActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  collect_veloActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::collect_velo_data::collect_veloGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::collect_velo_data::collect_veloActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::collect_velo_data::collect_veloActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct collect_veloActionGoal_

typedef ::collect_velo_data::collect_veloActionGoal_<std::allocator<void> > collect_veloActionGoal;

typedef boost::shared_ptr< ::collect_velo_data::collect_veloActionGoal > collect_veloActionGoalPtr;
typedef boost::shared_ptr< ::collect_velo_data::collect_veloActionGoal const> collect_veloActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::collect_velo_data::collect_veloActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::collect_velo_data::collect_veloActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::collect_velo_data::collect_veloActionGoal_<ContainerAllocator1> & lhs, const ::collect_velo_data::collect_veloActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::collect_velo_data::collect_veloActionGoal_<ContainerAllocator1> & lhs, const ::collect_velo_data::collect_veloActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace collect_velo_data

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::collect_velo_data::collect_veloActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::collect_velo_data::collect_veloActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::collect_velo_data::collect_veloActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::collect_velo_data::collect_veloActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::collect_velo_data::collect_veloActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::collect_velo_data::collect_veloActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::collect_velo_data::collect_veloActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "92f91b175acb408cc1eab92caeb69232";
  }

  static const char* value(const ::collect_velo_data::collect_veloActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x92f91b175acb408cULL;
  static const uint64_t static_value2 = 0xc1eab92caeb69232ULL;
};

template<class ContainerAllocator>
struct DataType< ::collect_velo_data::collect_veloActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "collect_velo_data/collect_veloActionGoal";
  }

  static const char* value(const ::collect_velo_data::collect_veloActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::collect_velo_data::collect_veloActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"collect_veloGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: collect_velo_data/collect_veloGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"std_msgs/Bool enable_work\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Bool\n"
"bool data\n"
;
  }

  static const char* value(const ::collect_velo_data::collect_veloActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::collect_velo_data::collect_veloActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct collect_veloActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::collect_velo_data::collect_veloActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::collect_velo_data::collect_veloActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::collect_velo_data::collect_veloGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COLLECT_VELO_DATA_MESSAGE_COLLECT_VELOACTIONGOAL_H
