(cl:defpackage collect_velo_data-msg
  (:use )
  (:export
   "<COLLECT_VELOACTION>"
   "COLLECT_VELOACTION"
   "<COLLECT_VELOACTIONFEEDBACK>"
   "COLLECT_VELOACTIONFEEDBACK"
   "<COLLECT_VELOACTIONGOAL>"
   "COLLECT_VELOACTIONGOAL"
   "<COLLECT_VELOACTIONRESULT>"
   "COLLECT_VELOACTIONRESULT"
   "<COLLECT_VELOFEEDBACK>"
   "COLLECT_VELOFEEDBACK"
   "<COLLECT_VELOGOAL>"
   "COLLECT_VELOGOAL"
   "<COLLECT_VELORESULT>"
   "COLLECT_VELORESULT"
  ))

