; Auto-generated. Do not edit!


(cl:in-package collect_velo_data-msg)


;//! \htmlinclude collect_veloFeedback.msg.html

(cl:defclass <collect_veloFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass collect_veloFeedback (<collect_veloFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <collect_veloFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'collect_veloFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name collect_velo_data-msg:<collect_veloFeedback> is deprecated: use collect_velo_data-msg:collect_veloFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <collect_veloFeedback>) ostream)
  "Serializes a message object of type '<collect_veloFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <collect_veloFeedback>) istream)
  "Deserializes a message object of type '<collect_veloFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<collect_veloFeedback>)))
  "Returns string type for a message object of type '<collect_veloFeedback>"
  "collect_velo_data/collect_veloFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'collect_veloFeedback)))
  "Returns string type for a message object of type 'collect_veloFeedback"
  "collect_velo_data/collect_veloFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<collect_veloFeedback>)))
  "Returns md5sum for a message object of type '<collect_veloFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'collect_veloFeedback)))
  "Returns md5sum for a message object of type 'collect_veloFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<collect_veloFeedback>)))
  "Returns full string definition for message of type '<collect_veloFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'collect_veloFeedback)))
  "Returns full string definition for message of type 'collect_veloFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <collect_veloFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <collect_veloFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'collect_veloFeedback
))
