; Auto-generated. Do not edit!


(cl:in-package collect_velo_data-msg)


;//! \htmlinclude collect_veloGoal.msg.html

(cl:defclass <collect_veloGoal> (roslisp-msg-protocol:ros-message)
  ((enable_work
    :reader enable_work
    :initarg :enable_work
    :type std_msgs-msg:Bool
    :initform (cl:make-instance 'std_msgs-msg:Bool)))
)

(cl:defclass collect_veloGoal (<collect_veloGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <collect_veloGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'collect_veloGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name collect_velo_data-msg:<collect_veloGoal> is deprecated: use collect_velo_data-msg:collect_veloGoal instead.")))

(cl:ensure-generic-function 'enable_work-val :lambda-list '(m))
(cl:defmethod enable_work-val ((m <collect_veloGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader collect_velo_data-msg:enable_work-val is deprecated.  Use collect_velo_data-msg:enable_work instead.")
  (enable_work m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <collect_veloGoal>) ostream)
  "Serializes a message object of type '<collect_veloGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'enable_work) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <collect_veloGoal>) istream)
  "Deserializes a message object of type '<collect_veloGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'enable_work) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<collect_veloGoal>)))
  "Returns string type for a message object of type '<collect_veloGoal>"
  "collect_velo_data/collect_veloGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'collect_veloGoal)))
  "Returns string type for a message object of type 'collect_veloGoal"
  "collect_velo_data/collect_veloGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<collect_veloGoal>)))
  "Returns md5sum for a message object of type '<collect_veloGoal>"
  "e05fc3a46e278eaaa08c453de28eddc1")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'collect_veloGoal)))
  "Returns md5sum for a message object of type 'collect_veloGoal"
  "e05fc3a46e278eaaa08c453de28eddc1")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<collect_veloGoal>)))
  "Returns full string definition for message of type '<collect_veloGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%std_msgs/Bool enable_work~%~%================================================================================~%MSG: std_msgs/Bool~%bool data~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'collect_veloGoal)))
  "Returns full string definition for message of type 'collect_veloGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%std_msgs/Bool enable_work~%~%================================================================================~%MSG: std_msgs/Bool~%bool data~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <collect_veloGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'enable_work))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <collect_veloGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'collect_veloGoal
    (cl:cons ':enable_work (enable_work msg))
))
