// Auto-generated. Do not edit!

// (in-package collect_velo_data.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let std_msgs = _finder('std_msgs');

//-----------------------------------------------------------

class collect_veloGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.enable_work = null;
    }
    else {
      if (initObj.hasOwnProperty('enable_work')) {
        this.enable_work = initObj.enable_work
      }
      else {
        this.enable_work = new std_msgs.msg.Bool();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type collect_veloGoal
    // Serialize message field [enable_work]
    bufferOffset = std_msgs.msg.Bool.serialize(obj.enable_work, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type collect_veloGoal
    let len;
    let data = new collect_veloGoal(null);
    // Deserialize message field [enable_work]
    data.enable_work = std_msgs.msg.Bool.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'collect_velo_data/collect_veloGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'e05fc3a46e278eaaa08c453de28eddc1';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    std_msgs/Bool enable_work
    
    ================================================================================
    MSG: std_msgs/Bool
    bool data
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new collect_veloGoal(null);
    if (msg.enable_work !== undefined) {
      resolved.enable_work = std_msgs.msg.Bool.Resolve(msg.enable_work)
    }
    else {
      resolved.enable_work = new std_msgs.msg.Bool()
    }

    return resolved;
    }
};

module.exports = collect_veloGoal;
