// Auto-generated. Do not edit!

// (in-package collect_velo_data.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class collect_veloResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.result_rotation = null;
      this.ts_ptu = null;
      this.ts_rs = null;
    }
    else {
      if (initObj.hasOwnProperty('result_rotation')) {
        this.result_rotation = initObj.result_rotation
      }
      else {
        this.result_rotation = new geometry_msgs.msg.TransformStamped();
      }
      if (initObj.hasOwnProperty('ts_ptu')) {
        this.ts_ptu = initObj.ts_ptu
      }
      else {
        this.ts_ptu = new geometry_msgs.msg.TransformStamped();
      }
      if (initObj.hasOwnProperty('ts_rs')) {
        this.ts_rs = initObj.ts_rs
      }
      else {
        this.ts_rs = new geometry_msgs.msg.TransformStamped();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type collect_veloResult
    // Serialize message field [result_rotation]
    bufferOffset = geometry_msgs.msg.TransformStamped.serialize(obj.result_rotation, buffer, bufferOffset);
    // Serialize message field [ts_ptu]
    bufferOffset = geometry_msgs.msg.TransformStamped.serialize(obj.ts_ptu, buffer, bufferOffset);
    // Serialize message field [ts_rs]
    bufferOffset = geometry_msgs.msg.TransformStamped.serialize(obj.ts_rs, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type collect_veloResult
    let len;
    let data = new collect_veloResult(null);
    // Deserialize message field [result_rotation]
    data.result_rotation = geometry_msgs.msg.TransformStamped.deserialize(buffer, bufferOffset);
    // Deserialize message field [ts_ptu]
    data.ts_ptu = geometry_msgs.msg.TransformStamped.deserialize(buffer, bufferOffset);
    // Deserialize message field [ts_rs]
    data.ts_rs = geometry_msgs.msg.TransformStamped.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += geometry_msgs.msg.TransformStamped.getMessageSize(object.result_rotation);
    length += geometry_msgs.msg.TransformStamped.getMessageSize(object.ts_ptu);
    length += geometry_msgs.msg.TransformStamped.getMessageSize(object.ts_rs);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'collect_velo_data/collect_veloResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '593509ac84d519f457e1f20b78510e22';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result definition
    geometry_msgs/TransformStamped result_rotation
    geometry_msgs/TransformStamped ts_ptu
    geometry_msgs/TransformStamped ts_rs
    
    ================================================================================
    MSG: geometry_msgs/TransformStamped
    # This expresses a transform from coordinate frame header.frame_id
    # to the coordinate frame child_frame_id
    #
    # This message is mostly used by the 
    # <a href="http://wiki.ros.org/tf">tf</a> package. 
    # See its documentation for more information.
    
    Header header
    string child_frame_id # the frame id of the child frame
    Transform transform
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: geometry_msgs/Transform
    # This represents the transform between two coordinate frames in free space.
    
    Vector3 translation
    Quaternion rotation
    
    ================================================================================
    MSG: geometry_msgs/Vector3
    # This represents a vector in free space. 
    # It is only meant to represent a direction. Therefore, it does not
    # make sense to apply a translation to it (e.g., when applying a 
    # generic rigid transformation to a Vector3, tf2 will only apply the
    # rotation). If you want your data to be translatable too, use the
    # geometry_msgs/Point message instead.
    
    float64 x
    float64 y
    float64 z
    ================================================================================
    MSG: geometry_msgs/Quaternion
    # This represents an orientation in free space in quaternion form.
    
    float64 x
    float64 y
    float64 z
    float64 w
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new collect_veloResult(null);
    if (msg.result_rotation !== undefined) {
      resolved.result_rotation = geometry_msgs.msg.TransformStamped.Resolve(msg.result_rotation)
    }
    else {
      resolved.result_rotation = new geometry_msgs.msg.TransformStamped()
    }

    if (msg.ts_ptu !== undefined) {
      resolved.ts_ptu = geometry_msgs.msg.TransformStamped.Resolve(msg.ts_ptu)
    }
    else {
      resolved.ts_ptu = new geometry_msgs.msg.TransformStamped()
    }

    if (msg.ts_rs !== undefined) {
      resolved.ts_rs = geometry_msgs.msg.TransformStamped.Resolve(msg.ts_rs)
    }
    else {
      resolved.ts_rs = new geometry_msgs.msg.TransformStamped()
    }

    return resolved;
    }
};

module.exports = collect_veloResult;
